version: 2.0

jobs:
  info:
    docker:
      - image: z4nyx/docker:latest
    steps:
      - run: git clone --depth=1 https://github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME} -b ${CIRCLE_BRANCH} .
      - run: bash .circleci/info

  build1:
    docker:
      - image: najahi/oven:latest
    steps:
      - run: git clone --depth=1 https://github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME} -b ${CIRCLE_BRANCH} .
      - run: bash .circleci/build1

  build2:
    docker:
      - image: najahi/oven:proton
    steps:
      - run: git clone --depth=1 https://github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME} -b ${CIRCLE_BRANCH} .
      - run: bash .circleci/build2

workflows:
  version: 2
  build:
    jobs:
      - info
      - build1
      - build2
